# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: taurus
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2 #quay.io/phasetwo/phasetwo-keycloak:26.5.0
    command: 'start-dev --import-realm'
    volumes:
      - ./realm-config:/opt/keycloak/data/import
      - ./realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh
      - ./realm-config/keycloak-authenticator.jar:/opt/keycloak/providers/keycloak-authenticator.jar
      - ./realm-config/taurus-theme:/opt/keycloak/themes/taurus-theme:ro
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgresql
      - KC_DB_URL_DATABASE=taurus_keycloak
      - KC_DB_USERNAME=taurus
      - KC_DB_PASSWORD=password
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_MANAGEMENT_PORT=9990
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:9443:9443
    healthcheck:
      test: 'bash /opt/keycloak/health-check.sh'
      interval: 5s
      timeout: 5s
      # Increased retries due to slow Keycloak startup in GitHub Actions using MacOS
      retries: 50
      start_period: 10s
    labels:
      org.springframework.boot.ignore: true
